// Localized content for the Attitudinal Psyche style test.
// Self-contained i18n (en/zh/ja/ko) — independent of the generic test system.

import { ASPECT_LETTER } from './apEngine.js';

// Type archetype nicknames (kept identical across locales, like brand labels).
export const TYPE_NICKNAMES = {
  VLEF: 'The Commander',
  VLFE: 'The Strategist',
  VELF: 'The Champion',
  VEFL: 'The Motivator',
  VFLE: 'The Director',
  VFEL: 'The Sovereign',
  LVEF: 'The Mastermind',
  LVFE: 'The Architect',
  LEVF: 'The Scholar',
  LEFV: 'The Sage',
  LFVE: 'The Engineer',
  LFEV: 'The Analyst',
  EVLF: 'The Advocate',
  EVFL: 'The Performer',
  ELVF: 'The Muse',
  ELFV: 'The Storyteller',
  EFVL: 'The Artist',
  EFLV: 'The Empath',
  FVLE: 'The Craftsman',
  FVEL: 'The Maker',
  FLVE: 'The Technician',
  FLEV: 'The Naturalist',
  FEVL: 'The Aesthete',
  FELV: 'The Caregiver',
};

const AP_CONTENT = {
  en: {
    ui: {
      kicker: 'Attitudinal Psyche',
      title: 'Attitudinal Psyche Test',
      intro:
        'Rate how much each statement is like you and discover your Attitudinal Psyche type — the order of Volition, Logic, Emotion, and Physics that shapes how you meet the world. Free, instant, and no sign-up.',
      instruction: 'For each statement, pick how much you agree — from strongly disagree to strongly agree.',
      scaleLabels: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
      progressReady: 'All set — reveal your type.',
      progressLocked: 'Answer every statement to unlock your type.',
      showResult: 'Show my type',
      answeredLabel: (answered, total) => `${answered} of ${total} answered`,
      resultKicker: 'Your Attitudinal Psyche type',
      energyTitle: 'Your aspect energy',
      energyNote: 'How much confident energy you invest in each aspect, from your answers.',
      mapTitle: 'Your position map',
      mapNote: 'Every aspect lands in one of four positions along two axes.',
      axisConfident: 'Confident',
      axisUnconfident: 'Unconfident',
      axisResult: 'Result',
      axisProcess: 'Process',
      breakdownTitle: 'Position by position',
      aspectsTitle: 'The four aspects',
      positionsTitle: 'What the four positions mean',
      caveat:
        'This is a self-typing style estimate, not a clinical assessment. Read the type as a mirror for reflection and compare it with your real behavior.',
      faqTitle: 'Attitudinal Psyche FAQ',
      retake: 'Retake test',
      shareText: (code, nickname) => `My Attitudinal Psyche type is ${code} — ${nickname}.`,
      cardTag: 'Attitudinal Psyche type',
      copyLink: 'Copy result link',
      linkCopied: 'Link copied',
    },
    statements: {
      s1: 'I know what I want and trust myself to set my own direction.',
      s5: 'I trust my own decisions and rarely need approval to act.',
      s9: 'Once I decide on something, I pursue it with strong will.',
      s13: 'Taking charge and leading feels natural to me.',
      s17: 'My independence and personal goals matter deeply to me.',
      s2: 'I trust my own reasoning, even against authority.',
      s6: 'I enjoy analyzing problems until the logic is clear.',
      s10: 'Being accurate and factually right matters a lot to me.',
      s14: 'I like debating ideas and testing whether they hold up.',
      s18: 'I judge claims by evidence more than by feelings.',
      s3: 'I enjoy exchanging feelings with others and value their response.',
      s7: 'I express my emotions openly and read moods easily.',
      s11: 'Relationships and emotional connection are central to my life.',
      s15: 'I quickly sense the emotional atmosphere in a room.',
      s19: 'What things mean emotionally guides many of my choices.',
      s4: 'Comfort, health, and my surroundings strongly affect me.',
      s8: 'I enjoy food, rest, movement, and sensory pleasures.',
      s12: 'I handle practical, hands-on tasks with confidence.',
      s16: 'Aesthetics, style, and how things look matter to me.',
      s20: 'I pay close attention to money, resources, and material security.',
    },
    aspects: {
      volition: { label: 'Volition', def: 'Willpower, ambition, identity, and the drive to choose your own direction.' },
      logic: { label: 'Logic', def: 'Reasoning, analysis, truth, and how you evaluate what makes sense.' },
      emotion: { label: 'Emotion', def: 'Feeling, expression, relationships, and what things mean to you.' },
      physics: { label: 'Physics', def: 'The body and material world: comfort, health, resources, and aesthetics.' },
    },
    positions: {
      confident: { ordinal: '1st', name: 'Confident', tagline: 'Strong · self-assured', def: 'You own this aspect, act on it without needing input, and treat your answer as the answer.' },
      flexible: { ordinal: '2nd', name: 'Flexible', tagline: 'Strong · open', def: 'Your most social strength: you engage this aspect through dialogue, adapt easily, and enjoy the back-and-forth.' },
      insecure: { ordinal: '3rd', name: 'Insecure', tagline: 'Sensitive · searching', def: 'You care deeply here but doubt yourself, seek reassurance, and can get defensive. Your biggest growth edge.' },
      unbothered: { ordinal: '4th', name: 'Unbothered', tagline: 'Quiet · indifferent', def: 'A blind spot you happily hand off. Low stress, but easy to neglect.' },
    },
    blocks: {
      volition: {
        confident: 'You lead with your will. You decide fast, hold your direction, and rarely need permission to act — just leave room for others to steer too.',
        flexible: 'You wield willpower with a light touch, setting direction while staying open to other goals. You negotiate and adapt without losing yourself.',
        insecure: 'Your sense of agency is tender. You can doubt what you really want or swing between control and surrender. Small chosen decisions rebuild trust in your will.',
        unbothered: "Ambition and control sit low on your list. You'd rather follow a good plan than fight for the wheel, and you rarely worry about status or power.",
      },
      logic: {
        confident: "You trust your reasoning. You reach verdicts quickly, state them plainly, and don't need consensus to feel right — watch for closing the case too soon.",
        flexible: 'You think out loud and enjoy it. You test ideas in dialogue, update happily, and treat being wrong as part of getting it right.',
        insecure: 'Being seen as smart matters more than you would like. You may over-research or defend your conclusions hard. Letting small errors be okay eases the pressure.',
        unbothered: "Abstract correctness doesn't grip you. You use whatever reasoning is handy and let others argue theory while you get on with life.",
      },
      emotion: {
        confident: "You own your feelings and read the room with authority. You set the emotional tone and express yourself without asking whether it's allowed.",
        flexible: 'You move fluidly through feeling — sharing, empathizing, and processing emotion openly with others, comfortable with both joy and grief.',
        insecure: 'Emotion feels high-stakes. You may worry about being liked, over-read moods, or hold feelings in until they spill. Naming them early keeps them your ally.',
        unbothered: "Mood and sentiment stay in the background. You're steady and unbothered by drama, though others may wish you would show more of what you feel.",
      },
      physics: {
        confident: "You're at home in the physical world, handling money, comfort, health, and hands-on tasks with easy confidence and clear taste.",
        flexible: 'You enjoy the sensory world and love to share it — cooking, building, styling, or caring for spaces, adapting comfort to whoever is around.',
        insecure: 'The material side can nag at you — health, looks, money, or "doing life right." You may over-worry or overspend to feel secure. Simple routines settle it.',
        unbothered: 'Comfort and appearances barely register. You can rough it, forget to eat, or ignore the mess — practical details are the first thing you delegate.',
      },
    },
    summary: (a1, a2, a3, a4) =>
      `You lead with ${a1} and set the tone. You stay open and collaborative in ${a2}, feel most exposed around ${a3}, and quietly set ${a4} aside.`,
    faq: [
      { q: 'What is Attitudinal Psyche?', a: 'Attitudinal Psyche (AP) is a typology that ranks four aspects — Volition, Logic, Emotion, and Physics — into four positions. Your order of these four is your type, such as VLEF.' },
      { q: 'What do the four letters mean?', a: 'Each letter is an aspect (V, L, E, F) placed in a position from 1st to 4th. The 1st is your confident lead, the 2nd is flexible and social, the 3rd is sensitive and insecure, and the 4th is unbothered.' },
      { q: 'Is this test free?', a: 'Yes — completely free, instant, and with no sign-up or email required. Your answers stay in your browser.' },
      { q: 'How accurate is a self-test?', a: 'A self-test is a starting estimate, not a verdict. Read your type as a mirror and compare it with how you actually behave across different situations.' },
      { q: 'How many types are there?', a: 'There are 24 types — every possible ordering of the four aspects (4 × 3 × 2 × 1).' },
    ],
  },

  zh: {
    ui: {
      kicker: '态度心理学',
      title: '态度心理学测试',
      intro:
        '为每句描述打分，找到你的态度心理学类型——意志、逻辑、情感、物质四个方面的排列顺序，决定了你面对世界的方式。免费、即时、无需注册。',
      instruction: '针对每句描述，选择你的同意程度——从「强烈不同意」到「强烈同意」。',
      scaleLabels: ['强烈不同意', '不同意', '中立', '同意', '强烈同意'],
      progressReady: '已完成——揭晓你的类型。',
      progressLocked: '答完所有描述即可解锁你的类型。',
      showResult: '查看我的类型',
      answeredLabel: (answered, total) => `${answered}/${total} 已答`,
      resultKicker: '你的态度心理学类型',
      energyTitle: '你的四方面能量',
      energyNote: '根据你的作答，你在每个方面投入的自信能量。',
      mapTitle: '你的位置图',
      mapNote: '每个方面都会落在两条坐标轴构成的四个位置之一。',
      axisConfident: '自信',
      axisUnconfident: '不自信',
      axisResult: '结果',
      axisProcess: '过程',
      breakdownTitle: '逐个位置解读',
      aspectsTitle: '四个方面',
      positionsTitle: '四个位置的含义',
      caveat: '这是一个自测风格估计，并非临床评估。请把结果当作自我反思的镜子，并与你的真实行为对照。',
      faqTitle: '态度心理学常见问题',
      retake: '重新测试',
      shareText: (code, nickname) => `我的态度心理学类型是 ${code} —— ${nickname}。`,
      cardTag: '态度心理学类型',
      copyLink: '复制结果链接',
      linkCopied: '链接已复制',
    },
    statements: {
      s1: '我清楚自己想要什么，并相信自己能决定人生方向。',
      s5: '我相信自己的决定，很少需要他人认可才行动。',
      s9: '一旦下定决心，我就会全力以赴地去追求。',
      s13: '主导与带领对我来说很自然。',
      s17: '独立和个人目标对我非常重要。',
      s2: '我相信自己的判断和推理，即使权威持不同意见。',
      s6: '我喜欢分析问题，直到逻辑清晰为止。',
      s10: '准确、事实正确对我很重要。',
      s14: '我喜欢辩论观点，检验它们是否站得住脚。',
      s18: '比起感受，我更依据证据来判断说法。',
      s3: '我喜欢与人交流情绪、共情彼此，也在意对方的回应。',
      s7: '我会坦率地表达情绪，也容易读懂气氛。',
      s11: '关系与情感联结是我生活的核心。',
      s15: '我能很快感知到一个空间里的情绪氛围。',
      s19: '事情在情感上的意义，指引着我的许多选择。',
      s4: '舒适、健康和周围环境会强烈影响我。',
      s8: '我享受美食、休息、运动和感官愉悦。',
      s12: '我能自信地处理实际、动手的事务。',
      s16: '美感、风格和事物的外观对我很重要。',
      s20: '我很关注金钱、资源和物质上的安全感。',
    },
    aspects: {
      volition: { label: '意志', def: '意志力、抱负、身份认同，以及选择自己方向的驱动力。' },
      logic: { label: '逻辑', def: '推理、分析、真相，以及你判断事情是否合理的方式。' },
      emotion: { label: '情感', def: '感受、表达、人际关系，以及事物对你的意义。' },
      physics: { label: '物质', def: '身体与物质世界：舒适、健康、资源和美感。' },
    },
    positions: {
      confident: { ordinal: '第 1', name: '自信', tagline: '强 · 笃定', def: '你掌控这个方面，无需他人输入就能行动，把自己的答案当作定论。' },
      flexible: { ordinal: '第 2', name: '灵活', tagline: '强 · 开放', def: '你最擅长的社交优势：你通过对话运用这个方面，轻松适应，享受来回交流。' },
      insecure: { ordinal: '第 3', name: '不安', tagline: '敏感 · 求索', def: '你在这里很在意却又自我怀疑，渴望被肯定，也容易变得防备。这是你最大的成长点。' },
      unbothered: { ordinal: '第 4', name: '无谓', tagline: '安静 · 淡然', def: '一个你乐于交给别人的盲区。压力很小，但也容易被忽视。' },
    },
    blocks: {
      volition: {
        confident: '你以意志主导。你决断迅速、坚持方向，很少需要别人许可才行动——只要记得给别人也留出掌舵的空间。',
        flexible: '你运用意志力时张弛有度，既设定方向，也对别人的目标保持开放。你会协商、会适应，却不迷失自己。',
        insecure: '你的自主感有些脆弱。你可能不确定自己真正想要什么，在掌控与放手之间摇摆。一个个小小的自主决定，能重建你对意志的信任。',
        unbothered: '抱负与掌控在你心里排位很低。比起争抢方向盘，你更愿意跟着一个好计划走，也很少在意地位或权力。',
      },
      logic: {
        confident: '你信任自己的推理。你能快速得出结论、直白表达，无需共识也觉得自己没错——但要留意别过早地盖棺定论。',
        flexible: '你喜欢把想法说出来。你在对话中检验观点，乐于修正，把「错」看作走向「对」的一部分。',
        insecure: '「被看作聪明」对你比你愿意承认的更重要。你可能过度查证，或死守自己的结论。允许小错误的存在，能减轻这份压力。',
        unbothered: '抽象的对错抓不住你。你会用手边现成的道理，把理论之争留给别人，自己继续过日子。',
      },
      emotion: {
        confident: '你掌控自己的情绪，也能笃定地读懂现场。你定下情感基调，表达自己时不必先问「可不可以」。',
        flexible: '你在情感中流动自如——分享、共情、坦然地与他人一起处理情绪，无论喜悦还是悲伤都能承接。',
        insecure: '情感对你风险很高。你可能担心不被喜欢、过度解读气氛，或把感受憋到爆发。及早说出感受，能让它成为你的盟友。',
        unbothered: '情绪与情感留在背景里。你稳定、不被戏剧化牵动，尽管别人有时希望你多流露一些真实感受。',
      },
      physics: {
        confident: '你在物质世界里如鱼得水，对金钱、舒适、健康和动手的活儿都从容自信，品味清晰。',
        flexible: '你享受感官世界，也乐于分享——做饭、动手、打扮、照料空间，并根据身边的人调整舒适度。',
        insecure: '物质那一面会时不时困扰你——健康、外表、金钱，或「把日子过对」。你可能过度担忧或超支来求安心。简单的日常规律能安定它。',
        unbothered: '舒适与外表几乎不在你的雷达上。你能将就、会忘记吃饭、也不在意乱——实际琐事是你第一个交出去的事。',
      },
    },
    summary: (a1, a2, a3, a4) =>
      `你以${a1}主导，定下基调；在${a2}上开放协作、游刃有余；面对${a3}时最为敏感、患得患失；而把${a4}放在最后，几乎不去在意。`,
    faq: [
      { q: '什么是态度心理学？', a: '态度心理学（Attitudinal Psyche，AP）是一种类型学，把意志、逻辑、情感、物质四个方面排成四个位置。这四者的顺序就是你的类型，例如 VLEF。' },
      { q: '这四个字母代表什么？', a: '每个字母是一个方面（V、L、E、F），被放在第 1 到第 4 的位置。第 1 是你自信主导的方面，第 2 灵活而擅长社交，第 3 敏感而不安，第 4 则淡然无谓。' },
      { q: '这个测试免费吗？', a: '完全免费、即时出结果，无需注册或邮箱。你的答案只保存在你的浏览器里。' },
      { q: '自测准确吗？', a: '自测是一个起点估计，而非定论。把结果当作镜子，并与你在不同情境中的真实行为对照。' },
      { q: '一共有多少种类型？', a: '共有 24 种——四个方面所有可能的排列（4 × 3 × 2 × 1）。' },
    ],
  },

  ja: {
    ui: {
      kicker: 'アティテュード・サイキ',
      title: 'アティテュード・サイキ診断',
      intro:
        '各記述がどれくらい自分に近いか評価して、あなたのアティテュード・サイキ・タイプを見つけましょう。意志・論理・感情・物質の順序が、世界との向き合い方を形づくります。無料・即時・登録不要。',
      instruction: '各記述について、同意の度合いを選んでください——「強く反対」から「強く賛成」まで。',
      scaleLabels: ['強く反対', '反対', 'どちらでもない', '賛成', '強く賛成'],
      progressReady: '完了 — タイプを表示します。',
      progressLocked: 'すべての記述に答えるとタイプが表示されます。',
      showResult: 'タイプを見る',
      answeredLabel: (answered, total) => `${answered}/${total} 回答済み`,
      resultKicker: 'あなたのアティテュード・サイキ・タイプ',
      energyTitle: '4つの側面のエネルギー',
      energyNote: '回答から算出した、各側面に注ぐ自信のエネルギーです。',
      mapTitle: 'あなたのポジション・マップ',
      mapNote: '各側面は2つの軸がつくる4つのポジションのいずれかに収まります。',
      axisConfident: '自信あり',
      axisUnconfident: '自信なし',
      axisResult: '結果',
      axisProcess: '過程',
      breakdownTitle: 'ポジション別の解説',
      aspectsTitle: '4つの側面',
      positionsTitle: '4つのポジションの意味',
      caveat: 'これは自己診断によるスタイルの推定であり、臨床的評価ではありません。結果は内省の鏡として捉え、実際の行動と照らし合わせてください。',
      faqTitle: 'アティテュード・サイキ よくある質問',
      retake: 'もう一度診断する',
      shareText: (code, nickname) => `私のアティテュード・サイキ・タイプは ${code} — ${nickname} です。`,
      cardTag: 'アティテュード・サイキ・タイプ',
      copyLink: '結果リンクをコピー',
      linkCopied: 'コピーしました',
    },
    statements: {
      s1: '自分が何を望むか分かっていて、進む方向を自分で決められると信じている。',
      s5: '自分の決定を信じ、行動するのに他人の承認をあまり必要としない。',
      s9: 'いったん決めたら、強い意志で追い求める。',
      s13: '主導し、率いることが自分には自然だ。',
      s17: '自立と個人的な目標が自分にとって非常に大切だ。',
      s2: '権威が反対しても、自分の推論を信じる。',
      s6: '論理が明確になるまで問題を分析するのが好きだ。',
      s10: '正確であること、事実として正しいことが自分には重要だ。',
      s14: '考えを議論し、それが成り立つか試すのが好きだ。',
      s18: '感情よりも証拠に基づいて主張を判断する。',
      s3: '人と感情を交わし共感し合うのが好きで、相手の反応も気にする。',
      s7: '感情を率直に表現し、その場の雰囲気を読み取りやすい。',
      s11: '人間関係と感情的なつながりが人生の中心だ。',
      s15: 'その場の感情的な空気をすぐに感じ取る。',
      s19: '物事の感情的な意味が、多くの選択を導いている。',
      s4: '快適さ・健康・身の回りの環境に強く影響される。',
      s8: '食事・休息・運動・感覚的な喜びを楽しむ。',
      s12: '実際的で手を動かす作業を自信を持ってこなす。',
      s16: '美しさ・スタイル・見た目が自分には重要だ。',
      s20: 'お金・資源・物質的な安心に強く注意を払う。',
    },
    aspects: {
      volition: { label: '意志', def: '意志力・野心・アイデンティティ、そして自分の方向を選ぶ原動力。' },
      logic: { label: '論理', def: '推論・分析・真実、そして何が筋が通るかを評価する仕方。' },
      emotion: { label: '感情', def: '感じること・表現・人間関係、そして物事の意味。' },
      physics: { label: '物質', def: '身体と物質世界：快適さ・健康・資源・美。' },
    },
    positions: {
      confident: { ordinal: '第1', name: '自信', tagline: '強い · 確信', def: 'この側面を自分のものとし、他者の助言なしに行動し、自分の答えを結論として扱います。' },
      flexible: { ordinal: '第2', name: '柔軟', tagline: '強い · 開放的', def: '最も社交的な強み。対話を通じてこの側面を働かせ、容易に適応し、やり取りを楽しみます。' },
      insecure: { ordinal: '第3', name: '不安', tagline: '繊細 · 模索', def: 'ここでは深く気にかけつつも自分を疑い、安心を求め、時に身構えます。最大の成長点です。' },
      unbothered: { ordinal: '第4', name: '無頓着', tagline: '静か · 淡白', def: '喜んで人に委ねる盲点。ストレスは少ないが、おろそかになりやすい領域です。' },
    },
    blocks: {
      volition: {
        confident: '意志で主導します。素早く決め、方向を保ち、行動に許可をほとんど必要としません——ただ、他者にも舵を握る余地を残しましょう。',
        flexible: '意志を軽やかに用い、方向を定めつつ他者の目標にも開かれています。自分を見失わずに交渉し、適応します。',
        insecure: '自律の感覚は繊細です。本当に望むものが分からず、支配と放棄の間で揺れることも。小さな自分の決定が、意志への信頼を取り戻します。',
        unbothered: '野心や支配は優先順位が低めです。舵を争うより良い計画に従うほうを好み、地位や権力をあまり気にしません。',
      },
      logic: {
        confident: '自分の推論を信じます。素早く結論に達し、率直に述べ、合意がなくても正しいと感じます——ただ、早すぎる結論には注意を。',
        flexible: '声に出して考えるのを楽しみます。対話でアイデアを試し、喜んで修正し、間違いを「正しさ」への過程と捉えます。',
        insecure: '「賢いと見られること」が思う以上に重要です。過度に調べたり、結論を強く守ったりしがち。小さな誤りを許すと楽になります。',
        unbothered: '抽象的な正しさには惹かれません。手近な理屈を使い、理論の争いは他者に任せて、自分は生活を進めます。',
      },
      emotion: {
        confident: '自分の感情を掌握し、確信を持って場を読みます。感情のトーンを定め、「許されるか」を問わずに表現します。',
        flexible: '感情の中を流れるように動きます——分かち合い、共感し、喜びも悲しみも他者と共に開かれて処理します。',
        insecure: '感情は高リスクに感じられます。好かれるか気にし、雰囲気を読みすぎ、感情を溜めて溢れさせることも。早く言葉にすれば味方になります。',
        unbothered: '気分や情緒は背景に留まります。安定していてドラマに動じませんが、もっと感情を見せてほしいと思われることも。',
      },
      physics: {
        confident: '物質世界に居心地よくいます。お金・快適さ・健康・手を動かす作業を、余裕ある自信と明確なセンスでこなします。',
        flexible: '感覚の世界を楽しみ、分かち合うのが好きです——料理・工作・装い・空間の手入れを、周りに合わせて調整します。',
        insecure: '物質面が気にかかります——健康・見た目・お金・「きちんと生きること」。安心のため過度に心配・散財することも。簡単な習慣が落ち着かせます。',
        unbothered: '快適さや見た目はほとんど意識に上りません。粗末でも平気、食事を忘れ、散らかりも気にせず——実務の細部は真っ先に人に任せます。',
      },
    },
    summary: (a1, a2, a3, a4) =>
      `あなたは${a1}を軸に自信を持って進み、${a2}では柔軟に人と関わり、${a3}には最も敏感で不安を感じやすく、${a4}は静かに後回しにします。`,
    faq: [
      { q: 'アティテュード・サイキとは？', a: 'アティテュード・サイキ（AP）は、意志・論理・感情・物質の4側面を4つのポジションに並べる類型論です。この順序があなたのタイプ（例：VLEF）になります。' },
      { q: '4つの文字の意味は？', a: '各文字は側面（V・L・E・F）で、第1〜第4のポジションに置かれます。第1は自信ある主導、第2は柔軟で社交的、第3は繊細で不安、第4は淡白で無頓着です。' },
      { q: 'この診断は無料ですか？', a: 'はい。完全無料・即時、登録やメール不要です。回答はブラウザ内にのみ保存されます。' },
      { q: '自己診断はどのくらい正確？', a: '自己診断は出発点の推定であり、断定ではありません。結果を鏡として、様々な状況での実際の行動と照らし合わせてください。' },
      { q: 'タイプはいくつ？', a: '24種類——4側面のすべての並び（4×3×2×1）です。' },
    ],
  },

  ko: {
    ui: {
      kicker: '애티튜디널 사이키',
      title: '애티튜디널 사이키 테스트',
      intro:
        '각 문장이 얼마나 나와 비슷한지 평가해 애티튜디널 사이키 유형을 찾아보세요. 의지·논리·감정·물질의 순서가 세상을 대하는 방식을 만듭니다. 무료, 즉시, 가입 불필요.',
      instruction: '각 문장에 대해 동의 정도를 선택하세요 — "매우 비동의"부터 "매우 동의"까지.',
      scaleLabels: ['매우 비동의', '비동의', '중립', '동의', '매우 동의'],
      progressReady: '완료 — 유형을 확인하세요.',
      progressLocked: '모든 문항에 답하면 유형이 열립니다.',
      showResult: '내 유형 보기',
      answeredLabel: (answered, total) => `${total}문항 중 ${answered} 응답`,
      resultKicker: '당신의 애티튜디널 사이키 유형',
      energyTitle: '네 측면의 에너지',
      energyNote: '답변에서 계산한, 각 측면에 쏟는 자신감 에너지입니다.',
      mapTitle: '나의 포지션 맵',
      mapNote: '각 측면은 두 축이 만드는 네 포지션 중 하나에 놓입니다.',
      axisConfident: '자신 있음',
      axisUnconfident: '자신 없음',
      axisResult: '결과',
      axisProcess: '과정',
      breakdownTitle: '포지션별 해설',
      aspectsTitle: '네 가지 측면',
      positionsTitle: '네 포지션의 의미',
      caveat: '이것은 자가 진단에 따른 스타일 추정이며 임상 평가가 아닙니다. 결과를 성찰의 거울로 삼아 실제 행동과 비교해 보세요.',
      faqTitle: '애티튜디널 사이키 자주 묻는 질문',
      retake: '다시 테스트',
      shareText: (code, nickname) => `내 애티튜디널 사이키 유형은 ${code} — ${nickname} 입니다.`,
      cardTag: '애티튜디널 사이키 유형',
      copyLink: '결과 링크 복사',
      linkCopied: '링크 복사됨',
    },
    statements: {
      s1: '나는 내가 무엇을 원하는지 알고, 스스로 방향을 정할 수 있다고 믿는다.',
      s5: '나는 내 결정을 신뢰하며, 행동하는 데 남의 승인이 거의 필요 없다.',
      s9: '한번 마음먹으면 강한 의지로 밀고 나간다.',
      s13: '주도하고 이끄는 것이 나에게는 자연스럽다.',
      s17: '독립과 개인적인 목표가 나에게 매우 중요하다.',
      s2: '권위가 반대해도 나는 내 추론을 믿는다.',
      s6: '논리가 명확해질 때까지 문제를 분석하는 것을 즐긴다.',
      s10: '정확하고 사실에 맞는 것이 나에게 중요하다.',
      s14: '생각을 토론하고 그것이 성립하는지 시험하는 것을 좋아한다.',
      s18: '나는 감정보다 증거로 주장을 판단한다.',
      s3: '나는 사람들과 감정을 나누고 공감하며, 상대의 반응도 중요하게 여긴다.',
      s7: '나는 감정을 솔직하게 표현하고 분위기를 잘 읽는다.',
      s11: '관계와 정서적 유대가 내 삶의 중심이다.',
      s15: '나는 공간의 감정적 분위기를 빠르게 감지한다.',
      s19: '사물의 정서적 의미가 내 많은 선택을 이끈다.',
      s4: '편안함, 건강, 주변 환경이 나에게 큰 영향을 준다.',
      s8: '나는 음식, 휴식, 운동, 감각적 즐거움을 즐긴다.',
      s12: '나는 실용적이고 직접 하는 일을 자신 있게 해낸다.',
      s16: '미적 감각, 스타일, 겉모습이 나에게 중요하다.',
      s20: '나는 돈, 자원, 물질적 안정에 많은 주의를 기울인다.',
    },
    aspects: {
      volition: { label: '의지', def: '의지력, 야망, 정체성, 그리고 자기 방향을 선택하는 추진력.' },
      logic: { label: '논리', def: '추론, 분석, 진실, 그리고 무엇이 타당한지 평가하는 방식.' },
      emotion: { label: '감정', def: '느낌, 표현, 관계, 그리고 사물이 지니는 의미.' },
      physics: { label: '물질', def: '신체와 물질 세계: 편안함, 건강, 자원, 미학.' },
    },
    positions: {
      confident: { ordinal: '1st', name: '자신', tagline: '강함 · 확신', def: '이 측면을 자신의 것으로 삼아 조언 없이 행동하고, 자신의 답을 결론으로 여깁니다.' },
      flexible: { ordinal: '2nd', name: '유연', tagline: '강함 · 개방', def: '가장 사교적인 강점. 대화를 통해 이 측면을 발휘하고 쉽게 적응하며 주고받음을 즐깁니다.' },
      insecure: { ordinal: '3rd', name: '불안', tagline: '예민 · 탐색', def: '여기서는 깊이 신경 쓰면서도 자신을 의심하고 안심을 구하며 때로 방어적입니다. 가장 큰 성장 지점입니다.' },
      unbothered: { ordinal: '4th', name: '무심', tagline: '조용 · 담담', def: '기꺼이 남에게 넘기는 사각지대. 스트레스는 적지만 소홀해지기 쉽습니다.' },
    },
    blocks: {
      volition: {
        confident: '당신은 의지로 이끕니다. 빠르게 결정하고 방향을 지키며 행동에 허락이 거의 필요 없습니다 — 다만 남에게도 키를 잡을 여지를 남기세요.',
        flexible: '의지를 가볍게 다뤄 방향을 정하면서도 타인의 목표에 열려 있습니다. 자신을 잃지 않고 협상하고 적응합니다.',
        insecure: '자율감이 섬세합니다. 진정 원하는 바를 의심하거나 통제와 내려놓음 사이를 오갈 수 있습니다. 작은 스스로의 결정이 의지에 대한 신뢰를 되찾아 줍니다.',
        unbothered: '야망과 통제는 우선순위가 낮습니다. 키를 다투기보다 좋은 계획을 따르길 선호하며 지위나 권력을 잘 신경 쓰지 않습니다.',
      },
      logic: {
        confident: '자신의 추론을 신뢰합니다. 빠르게 결론에 이르고 분명히 말하며 합의 없이도 옳다고 느낍니다 — 다만 너무 이른 단정은 주의하세요.',
        flexible: '소리 내어 생각하길 즐깁니다. 대화로 아이디어를 시험하고 기꺼이 수정하며 틀림을 옳음으로 가는 과정으로 여깁니다.',
        insecure: '"똑똑해 보이는 것"이 생각보다 중요합니다. 지나치게 조사하거나 결론을 강하게 방어하기 쉽습니다. 작은 오류를 허용하면 부담이 줄어듭니다.',
        unbothered: '추상적인 옳고 그름에 끌리지 않습니다. 손쉬운 논리를 쓰고 이론 다툼은 남에게 맡긴 채 삶을 이어갑니다.',
      },
      emotion: {
        confident: '자신의 감정을 장악하고 확신 있게 분위기를 읽습니다. 감정의 톤을 정하고 "괜찮은지" 묻지 않고 표현합니다.',
        flexible: '감정 속을 유연하게 흐릅니다 — 나누고 공감하며 기쁨도 슬픔도 타인과 함께 열린 채 다룹니다.',
        insecure: '감정은 위험 부담이 큽니다. 호감을 걱정하고 분위기를 과하게 읽거나 감정을 참다 터뜨리기도 합니다. 일찍 말로 표현하면 감정이 아군이 됩니다.',
        unbothered: '기분과 정서는 배경에 머뭅니다. 안정적이고 드라마에 흔들리지 않지만, 감정을 더 드러내길 바라는 이들도 있습니다.',
      },
      physics: {
        confident: '물질 세계가 편안합니다. 돈, 편안함, 건강, 직접 하는 일을 여유로운 자신감과 분명한 안목으로 다룹니다.',
        flexible: '감각의 세계를 즐기고 나누길 좋아합니다 — 요리, 만들기, 꾸미기, 공간 돌보기를 주변에 맞춰 조율합니다.',
        insecure: '물질적인 면이 신경 쓰입니다 — 건강, 외모, 돈, 혹은 "제대로 사는 것". 안심하려고 과하게 걱정하거나 지출하기도 합니다. 간단한 루틴이 안정시켜 줍니다.',
        unbothered: '편안함과 외모는 거의 의식되지 않습니다. 대충 지내도 괜찮고 끼니를 잊으며 어질러짐도 신경 쓰지 않습니다 — 실무의 세부는 가장 먼저 남에게 맡깁니다.',
      },
    },
    summary: (a1, a2, a3, a4) =>
      `당신은 ${a1}(으)로 주도하며 자신감을 보이고, ${a2}에서는 열린 자세로 협력하며, ${a3} 앞에서는 가장 예민하고 불안해지고, ${a4}은(는) 조용히 뒷전으로 둡니다.`,
    faq: [
      { q: '애티튜디널 사이키란?', a: '애티튜디널 사이키(AP)는 의지·논리·감정·물질 네 측면을 네 포지션으로 배열하는 유형론입니다. 이 순서가 곧 당신의 유형(예: VLEF)입니다.' },
      { q: '네 글자는 무엇을 뜻하나요?', a: '각 글자는 측면(V·L·E·F)이며 1st부터 4th까지의 포지션에 놓입니다. 1st는 자신 있는 주도, 2nd는 유연하고 사교적, 3rd는 예민하고 불안, 4th는 담담하고 무심합니다.' },
      { q: '이 테스트는 무료인가요?', a: '네 — 완전 무료이며 즉시 결과가 나오고 가입이나 이메일이 필요 없습니다. 답변은 브라우저에만 저장됩니다.' },
      { q: '자가 진단은 얼마나 정확한가요?', a: '자가 진단은 출발점 추정이지 단정이 아닙니다. 결과를 거울로 삼아 다양한 상황에서의 실제 행동과 비교해 보세요.' },
      { q: '유형은 몇 개인가요?', a: '24개입니다 — 네 측면의 모든 배열(4×3×2×1)입니다.' },
    ],
  },
};

export function getApContent(locale) {
  return AP_CONTENT[locale] || AP_CONTENT.en;
}

export { ASPECT_LETTER };
