export const MBTI_AVATAR_TYPES = [
  {
    type: 'INTJ',
    title: '战略建筑师',
    tone: '冷静、远见、系统化',
    palette: '深紫 / 蓝灰',
    essence: '把复杂目标拆成长期系统，偏好独立推演和高质量决策。',
    visualCues: ['建筑蓝图与几何模型', '克制站姿', '深色高领和结构化外套'],
    cardUse: '适合放在“长期规划、独立思考、策略优势”卡片里，强化理性、未来导向的第一印象。',
    prompts: ['我最想优化的系统是什么？', '我是否把推理过程太晚才分享给别人？'],
  },
  {
    type: 'INTP',
    title: '逻辑分析师',
    tone: '好奇、精准、抽象',
    palette: '蓝紫 / 墨色',
    essence: '喜欢拆解概念、验证假设，并追问一个想法背后的底层逻辑。',
    visualCues: ['笔记本与抽象图形', '若有所思的视线', '轻学术感服装'],
    cardUse: '适合承载“概念深度、问题拆解、持续探索”的内容，让卡片更像一张思维实验室。',
    prompts: ['这个问题真正的变量是什么？', '我是否因为追求完美而延迟完成？'],
  },
  {
    type: 'ENTJ',
    title: '指挥官',
    tone: '果断、组织、目标感',
    palette: '海军蓝 / 银灰',
    essence: '擅长把愿景变成路线图，并推动资源、角色和节奏向目标靠拢。',
    visualCues: ['地图、棋子、计划板', '开放肩线与直视姿态', '西装式轮廓'],
    cardUse: '适合用于“领导力、执行秩序、目标管理”分析卡，视觉上形成明确方向感。',
    prompts: ['我需要邀请谁更早提出反对意见？', '效率之外还有什么人的成本？'],
  },
  {
    type: 'ENTP',
    title: '创意辩手',
    tone: '机敏、发散、实验性',
    palette: '紫色 / 电光蓝',
    essence: '享受碰撞观点、测试新路径，并用快速联想找到更锋利的方案。',
    visualCues: ['便利贴、原型、显微装置', '动态手势', '轻松但不松散的穿搭'],
    cardUse: '适合放在“想法生成、辩论视角、创新突破”卡片，突出灵活和挑战惯性。',
    prompts: ['我是在推进问题，还是只是在追求新鲜？', '哪一个想法值得真正落地？'],
  },
  {
    type: 'INFJ',
    title: '洞察倡导者',
    tone: '温和、坚定、意义感',
    palette: '森林绿 / 暖金',
    essence: '擅长看见人的潜能，也会把价值观转化成安静但持久的行动。',
    visualCues: ['灯、书、本草感背景', '保护性的手势', '柔和但专注的表情'],
    cardUse: '适合承接“使命、共情、深层洞察”的内容，让读者感到被理解而不是被定义。',
    prompts: ['我真正想守护的价值是什么？', '我是否独自承担了太多情绪工作？'],
  },
  {
    type: 'INFP',
    title: '理想调停者',
    tone: '真诚、想象、价值驱动',
    palette: '鼠尾草绿 / 花园粉',
    essence: '重视真实自我与意义感，常用创作、文字或温柔支持表达内在信念。',
    visualCues: ['手账、花草、书本', '含蓄而梦幻的表情', '柔软材质与自然色'],
    cardUse: '最适合“哪个版本的 INFP 形象最代表你”这个问题：图像能把内在价值、敏感度和创造力变成可选择的版本。',
    prompts: ['我现在最想忠于哪一种内在声音？', '什么结构能保护我的理想不被消耗？'],
  },
  {
    type: 'ENFJ',
    title: '温暖引导者',
    tone: '鼓舞、连接、带动',
    palette: '蓝绿 / 暖光',
    essence: '自然地关注群体氛围，擅长把人聚到一个有意义的方向上。',
    visualCues: ['群体背景、教学或社区线索', '开放手势', '亲和而清晰的目光'],
    cardUse: '适合用于“沟通、带领、支持他人成长”卡片，视觉重点是关系的聚合力。',
    prompts: ['我是否替别人承担了本该他们选择的部分？', '我自己的边界在哪里？'],
  },
  {
    type: 'ENFP',
    title: '灵感发起者',
    tone: '热情、自由、可能性',
    palette: '青绿 / 明亮黄',
    essence: '用感染力打开新可能，擅长把人、故事和创意连接起来。',
    visualCues: ['彩色便利贴、头脑风暴墙', '大幅度表情与手势', '轻快高饱和外套'],
    cardUse: '适合“创意火花、关系能量、探索欲”卡片，让人格分析不只是静态结论。',
    prompts: ['我需要为哪一个想法保留持续行动？', '哪些选择只是短暂兴奋？'],
  },
  {
    type: 'ISTJ',
    title: '秩序执行者',
    tone: '可靠、细节、标准',
    palette: '米灰 / 靛蓝',
    essence: '重视事实、责任和可复用流程，习惯把承诺落实到稳定行动。',
    visualCues: ['文件夹、表格、整齐架子', '端正姿态', '低调实用的服装'],
    cardUse: '适合解释“责任感、规则意识、稳定交付”，卡片观感应清楚、安定、可信。',
    prompts: ['我正在维护的是必要标准，还是旧习惯？', '哪里可以给新方法留空间？'],
  },
  {
    type: 'ISFJ',
    title: '细致守护者',
    tone: '体贴、稳定、照顾',
    palette: '暖米 / 浅蓝',
    essence: '敏锐捕捉他人的实际需要，并用持续、具体的方式提供支持。',
    visualCues: ['护理、织物、杯子、家庭感物件', '温和低姿态', '柔软针织材质'],
    cardUse: '适合“服务、记忆细节、关系承诺”卡片，图像能让关怀不显得抽象。',
    prompts: ['我是否在安静地过度付出？', '我需要怎样请求帮助和认可？'],
  },
  {
    type: 'ESTJ',
    title: '高效管理者',
    tone: '直接、负责、推进',
    palette: '钢蓝 / 中性灰',
    essence: '喜欢明确标准、角色和进度，擅长把目标转成可衡量的执行。',
    visualCues: ['夹板、办公室、进度板', '挺直站姿', '正式外套'],
    cardUse: '适合用于“组织力、责任制、决策速度”卡片，帮助读者快速理解执行型优势。',
    prompts: ['我是否在听清楚之前就开始优化？', '规则是否适合当前情境？'],
  },
  {
    type: 'ESFJ',
    title: '社群照料者',
    tone: '外向、负责、归属感',
    palette: '天蓝 / 派对粉',
    essence: '通过实际照顾和清晰期待创造稳定的人际归属。',
    visualCues: ['聚会、甜点、欢迎场景', '友善互动姿态', '明亮柔和服装'],
    cardUse: '适合“团队照料、社交敏锐、关系维护”分析卡，图像要传达温暖和可依靠。',
    prompts: ['我是否把被喜欢等同于自我价值？', '我能否接纳更不传统的选择？'],
  },
  {
    type: 'ISTP',
    title: '冷静工匠',
    tone: '实操、独立、临场',
    palette: '炭黑 / 工具金属',
    essence: '通过动手测试理解世界，越接近真实问题越能保持冷静。',
    visualCues: ['扳手、机械零件、工作台', '放松但警觉的姿态', '皮革或工装材质'],
    cardUse: '适合“技能、危机冷静、现场解决问题”卡片，让分析更贴近行动场景。',
    prompts: ['我能否提前说明我的处理过程？', '哪些高风险事情需要更早计划？'],
  },
  {
    type: 'ISFP',
    title: '感受冒险家',
    tone: '审美、自由、体验',
    palette: '赭黄 / 自然绿',
    essence: '用感官、创作和当下体验表达自我，重视不被过度定义的自由。',
    visualCues: ['画板、自然风景、相机', '安静观察', '柔软层叠穿搭'],
    cardUse: '适合“审美直觉、个人节奏、温柔共情”卡片，让内容从文字走向生活感。',
    prompts: ['我长期想成为怎样的人？', '哪段冲突需要在积累前说出来？'],
  },
  {
    type: 'ESTP',
    title: '行动创业者',
    tone: '大胆、现实、机会感',
    palette: '珊瑚红 / 暖橙',
    essence: '快速读取现场并采取行动，擅长谈判、试错和抓住窗口期。',
    visualCues: ['城市、车、增长图、运动感', '前倾姿态', '明快外套和墨镜'],
    cardUse: '适合“即时判断、行动偏好、现实谈判”卡片，视觉上要有速度和机会感。',
    prompts: ['我是否低估了后果？', '哪些决定需要留下记录给团队？'],
  },
  {
    type: 'ESFP',
    title: '现场感染者',
    tone: '表达、热烈、陪伴',
    palette: '舞台粉 / 金色',
    essence: '把人带入当下体验，用真实热情、鼓励和表现力点亮场域。',
    visualCues: ['舞台灯、音乐、麦克风', '开放笑容', '闪光材质和明亮色'],
    cardUse: '适合“表达力、社交能量、实践鼓励”卡片，让结果页更有情绪记忆点。',
    prompts: ['我是否需要为未来做一点取舍？', '什么正在分散我的注意力？'],
  },
];

export const MBTI_AVATAR_TRANSLATIONS = {
  en: {
    INTJ: {
      title: 'Strategic Architect',
      tone: 'Calm, visionary, systematic',
      palette: 'Deep purple / blue gray',
      essence: 'Turns complex goals into long-range systems, preferring independent reasoning and high-quality decisions.',
      visualCues: ['Architectural blueprints and geometric models', 'Composed posture', 'Dark turtleneck and structured outerwear'],
      cardUse: 'Works well in cards about long-range planning, independent thinking, and strategic strengths, creating a rational future-focused first impression.',
      prompts: ['What system do I most want to optimize?', 'Am I sharing my reasoning too late?'],
    },
    INTP: {
      title: 'Logical Analyst',
      tone: 'Curious, precise, abstract',
      palette: 'Blue violet / ink',
      essence: 'Enjoys taking concepts apart, testing assumptions, and asking what logic sits underneath an idea.',
      visualCues: ['Notebook and abstract diagrams', 'Thoughtful gaze', 'Light academic clothing'],
      cardUse: 'Best for content about conceptual depth, problem decomposition, and continuous exploration, making the card feel like a thinking lab.',
      prompts: ['What are the real variables in this problem?', 'Am I delaying completion by chasing perfect clarity?'],
    },
    ENTJ: {
      title: 'Commander',
      tone: 'Decisive, organized, goal-driven',
      palette: 'Navy / silver gray',
      essence: 'Turns vision into a roadmap and aligns resources, roles, and tempo around the goal.',
      visualCues: ['Maps, chess pieces, planning board', 'Open shoulders and direct gaze', 'Tailored suit silhouette'],
      cardUse: 'Fits leadership, execution order, and goal-management cards with a clear sense of direction.',
      prompts: ['Who should I invite to disagree earlier?', 'What human cost exists beyond efficiency?'],
    },
    ENTP: {
      title: 'Creative Debater',
      tone: 'Quick, divergent, experimental',
      palette: 'Purple / electric blue',
      essence: 'Enjoys clashing viewpoints, testing new paths, and using rapid association to sharpen solutions.',
      visualCues: ['Sticky notes, prototypes, tiny devices', 'Animated gestures', 'Relaxed but intentional styling'],
      cardUse: 'Fits idea generation, debate perspective, and innovation cards, highlighting flexibility and challenge.',
      prompts: ['Am I moving the problem forward, or just chasing novelty?', 'Which idea deserves real execution?'],
    },
    INFJ: {
      title: 'Insightful Advocate',
      tone: 'Gentle, firm, meaning-led',
      palette: 'Forest green / warm gold',
      essence: 'Sees people’s potential and turns values into quiet but persistent action.',
      visualCues: ['Lamp, books, botanical background', 'Protective hand gesture', 'Soft but focused expression'],
      cardUse: 'Supports cards about mission, empathy, and deep insight, helping readers feel understood rather than labeled.',
      prompts: ['What value do I truly want to protect?', 'Am I carrying too much emotional work alone?'],
    },
    INFP: {
      title: 'Idealistic Mediator',
      tone: 'Sincere, imaginative, values-driven',
      palette: 'Sage green / garden pink',
      essence: 'Values authenticity and meaning, often expressing inner convictions through creation, writing, or gentle support.',
      visualCues: ['Journal, flowers, books', 'Reserved and dreamy expression', 'Soft textures and natural colors'],
      cardUse: 'Best for “which INFP avatar represents you”: the image turns inner values, sensitivity, and creativity into selectable versions.',
      prompts: ['Which inner voice do I most want to honor now?', 'What structure can protect my ideals from burnout?'],
    },
    ENFJ: {
      title: 'Warm Guide',
      tone: 'Encouraging, connecting, mobilizing',
      palette: 'Blue green / warm light',
      essence: 'Naturally reads group atmosphere and gathers people toward a meaningful direction.',
      visualCues: ['Group, teaching, or community cues', 'Open gestures', 'Warm and clear eye contact'],
      cardUse: 'Fits communication, leading, and supporting growth cards with visual emphasis on connection.',
      prompts: ['Am I carrying choices that belong to others?', 'Where are my own boundaries?'],
    },
    ENFP: {
      title: 'Inspirational Starter',
      tone: 'Enthusiastic, free, possibility-led',
      palette: 'Teal / bright yellow',
      essence: 'Opens new possibilities with contagious energy, connecting people, stories, and ideas.',
      visualCues: ['Colorful notes and brainstorming wall', 'Big expressions and gestures', 'Light, saturated outerwear'],
      cardUse: 'Fits creative spark, relational energy, and exploration cards so analysis feels dynamic rather than static.',
      prompts: ['Which idea needs sustained action?', 'Which options are only temporary excitement?'],
    },
    ISTJ: {
      title: 'Orderly Executor',
      tone: 'Reliable, detailed, standards-led',
      palette: 'Warm gray / indigo',
      essence: 'Values facts, responsibility, and repeatable process, turning commitments into steady action.',
      visualCues: ['Folders, spreadsheets, organized shelves', 'Upright posture', 'Practical understated clothing'],
      cardUse: 'Fits responsibility, rule awareness, and stable delivery cards with a clear, calm, trustworthy feel.',
      prompts: ['Am I maintaining a necessary standard or an old habit?', 'Where can I leave room for a new method?'],
    },
    ISFJ: {
      title: 'Careful Protector',
      tone: 'Considerate, steady, caring',
      palette: 'Warm beige / pale blue',
      essence: 'Notices practical needs and offers support in consistent, concrete ways.',
      visualCues: ['Care items, fabric, cup, home-like objects', 'Gentle low-key posture', 'Soft knit textures'],
      cardUse: 'Fits service, memory for details, and relationship commitment cards, making care feel concrete.',
      prompts: ['Am I quietly over-giving?', 'How can I ask for help and recognition?'],
    },
    ESTJ: {
      title: 'Efficient Manager',
      tone: 'Direct, responsible, driving',
      palette: 'Steel blue / neutral gray',
      essence: 'Likes clear standards, roles, and progress, converting goals into measurable execution.',
      visualCues: ['Clipboard, office, progress board', 'Straight posture', 'Formal jacket'],
      cardUse: 'Fits organization, accountability, and decision-speed cards, helping readers quickly understand execution strengths.',
      prompts: ['Am I optimizing before I have listened clearly?', 'Do the rules still fit this situation?'],
    },
    ESFJ: {
      title: 'Community Caregiver',
      tone: 'Outgoing, responsible, belonging-focused',
      palette: 'Sky blue / party pink',
      essence: 'Creates stable belonging through practical care and clear expectations.',
      visualCues: ['Gathering, desserts, welcoming scene', 'Friendly interactive posture', 'Bright soft clothing'],
      cardUse: 'Fits team care, social awareness, and relationship-maintenance cards with warmth and dependability.',
      prompts: ['Am I equating being liked with self-worth?', 'Can I accept less traditional choices?'],
    },
    ISTP: {
      title: 'Calm Craftsperson',
      tone: 'Hands-on, independent, situational',
      palette: 'Charcoal / tool metal',
      essence: 'Understands the world by testing it directly and stays calm closest to real problems.',
      visualCues: ['Wrench, mechanical parts, workbench', 'Relaxed but alert posture', 'Leather or utility fabric'],
      cardUse: 'Fits skill, crisis calm, and field problem-solving cards, grounding analysis in action.',
      prompts: ['Can I explain my process earlier?', 'Which high-stakes risks need earlier planning?'],
    },
    ISFP: {
      title: 'Sensitive Adventurer',
      tone: 'Aesthetic, free, experiential',
      palette: 'Ochre / natural green',
      essence: 'Expresses self through senses, creation, and present experience, valuing freedom from over-definition.',
      visualCues: ['Sketch board, natural scenery, camera', 'Quiet observation', 'Soft layered outfits'],
      cardUse: 'Fits aesthetic intuition, personal rhythm, and gentle empathy cards, moving content from text into lived feeling.',
      prompts: ['Who do I want to become over time?', 'Which conflict should be named before it builds up?'],
    },
    ESTP: {
      title: 'Action Entrepreneur',
      tone: 'Bold, realistic, opportunity-aware',
      palette: 'Coral red / warm orange',
      essence: 'Reads the situation quickly and acts, excelling at negotiation, trial and error, and timing.',
      visualCues: ['City, vehicle, growth chart, motion', 'Forward-leaning posture', 'Bright jacket and sunglasses'],
      cardUse: 'Fits real-time judgment, action preference, and practical negotiation cards with speed and opportunity.',
      prompts: ['Am I underestimating consequences?', 'Which decisions need to be documented for the team?'],
    },
    ESFP: {
      title: 'Live Spark',
      tone: 'Expressive, warm, companionable',
      palette: 'Stage pink / gold',
      essence: 'Brings people into the present moment and lights up the room with real warmth, encouragement, and expressiveness.',
      visualCues: ['Stage lights, music, microphone', 'Open smile', 'Shimmering material and bright color'],
      cardUse: 'Fits expression, social energy, and practical encouragement cards, giving results emotional memorability.',
      prompts: ['Do I need to trade something now for the future?', 'What is scattering my attention?'],
    },
  },
  ja: {
    INTJ: {
      title: '戦略アーキテクト',
      tone: '冷静、先見的、体系的',
      palette: '深い紫 / ブルーグレー',
      essence: '複雑な目標を長期的な仕組みに変え、独立した推論と質の高い判断を好みます。',
      visualCues: ['建築図面と幾何学モデル', '落ち着いた立ち姿', 'ダークなハイネックと構築的な上着'],
      cardUse: '長期計画、独立思考、戦略的強みのカードに適し、理性的で未来志向の第一印象を作ります。',
      prompts: ['いちばん最適化したい仕組みは何ですか？', '自分の推論を共有するのが遅すぎませんか？'],
    },
    INTP: {
      title: '論理アナリスト',
      tone: '好奇心、精密、抽象的',
      palette: '青紫 / インク色',
      essence: '概念を分解し、仮説を検証し、アイデアの根底にある論理を探ることを好みます。',
      visualCues: ['ノートと抽象図形', '考え込む視線', '軽いアカデミックな服装'],
      cardUse: '概念の深さ、問題分解、継続的な探索を伝えるカードに適し、思考実験室のような印象を作ります。',
      prompts: ['この問題の本当の変数は何ですか？', '完璧さを求めて完了を遅らせていませんか？'],
    },
    ENTJ: {
      title: '指揮官',
      tone: '決断力、組織力、目標志向',
      palette: 'ネイビー / シルバーグレー',
      essence: 'ビジョンをロードマップに変え、資源、役割、リズムを目標へ向けて整えます。',
      visualCues: ['地図、チェス、計画ボード', '開いた肩線とまっすぐな視線', 'スーツ風のシルエット'],
      cardUse: 'リーダーシップ、実行秩序、目標管理のカードに適し、明確な方向感を出します。',
      prompts: ['誰にもっと早く反対意見を求めるべきですか？', '効率以外にどんな人的コストがありますか？'],
    },
    ENTP: {
      title: '創造的ディベーター',
      tone: '機敏、発散的、実験的',
      palette: '紫 / エレクトリックブルー',
      essence: '意見をぶつけ、新しい道を試し、すばやい連想で解決策を鋭くします。',
      visualCues: ['付箋、プロトタイプ、小さな装置', '動きのある手振り', 'リラックスしつつ意図のある服装'],
      cardUse: '発想、議論の視点、革新突破のカードに適し、柔軟さと挑戦性を強調します。',
      prompts: ['問題を前に進めていますか、それとも新しさを追っているだけですか？', 'どのアイデアを本当に実行しますか？'],
    },
    INFJ: {
      title: '洞察の提唱者',
      tone: '穏やか、確固、意味重視',
      palette: 'フォレストグリーン / 暖かいゴールド',
      essence: '人の可能性を見抜き、価値観を静かで持続的な行動に変えます。',
      visualCues: ['ランプ、本、植物の背景', '守るような手の動き', '柔らかく集中した表情'],
      cardUse: '使命、共感、深い洞察のカードに適し、読者を定義するより理解される感覚を作ります。',
      prompts: ['本当に守りたい価値は何ですか？', '感情面の役割を一人で抱えすぎていませんか？'],
    },
    INFP: {
      title: '理想主義の調停者',
      tone: '誠実、想像力、価値主導',
      palette: 'セージグリーン / ガーデンピンク',
      essence: '本物らしさと意味を大切にし、創作、言葉、穏やかな支援で内面の信念を表します。',
      visualCues: ['手帳、花、本', '控えめで夢見がちな表情', '柔らかな素材と自然色'],
      cardUse: '「どのINFP像が自分らしいか」に最適で、内なる価値、敏感さ、創造性を選べる形にします。',
      prompts: ['今いちばん大切にしたい内なる声は何ですか？', '理想を消耗から守る構造は何ですか？'],
    },
    ENFJ: {
      title: '温かなガイド',
      tone: '励ます、つなぐ、動かす',
      palette: 'ブルーグリーン / 暖かな光',
      essence: '集団の空気を自然に読み、意味ある方向へ人を集めます。',
      visualCues: ['集団、教育、コミュニティの要素', '開いた手振り', '親しみやすく明確な視線'],
      cardUse: 'コミュニケーション、導き、成長支援のカードに適し、関係を集める力を見せます。',
      prompts: ['他人が選ぶべき部分まで背負っていませんか？', '自分の境界線はどこですか？'],
    },
    ENFP: {
      title: 'ひらめきのスターター',
      tone: '情熱、自由、可能性',
      palette: 'ティール / 明るい黄色',
      essence: '感染力のあるエネルギーで新しい可能性を開き、人、物語、アイデアをつなげます。',
      visualCues: ['カラフルな付箋とブレスト壁', '大きな表情と手振り', '軽快で鮮やかな上着'],
      cardUse: '創造の火花、関係エネルギー、探索欲のカードに適し、分析を静的な結論で終わらせません。',
      prompts: ['どのアイデアに継続行動を残すべきですか？', '一時的な高揚だけの選択はどれですか？'],
    },
    ISTJ: {
      title: '秩序ある実行者',
      tone: '信頼性、細部、基準重視',
      palette: 'ウォームグレー / インディゴ',
      essence: '事実、責任、再利用できる手順を重視し、約束を安定した行動に落とします。',
      visualCues: ['フォルダ、表、整った棚', '端正な姿勢', '実用的で控えめな服装'],
      cardUse: '責任感、規則意識、安定した納品を説明するカードに適し、明快で信頼できる印象を作ります。',
      prompts: ['守っているのは必要な基準ですか、古い習慣ですか？', '新しい方法に余白を残せる場所はどこですか？'],
    },
    ISFJ: {
      title: '丁寧な守り手',
      tone: '思いやり、安定、世話',
      palette: '暖かいベージュ / 淡い青',
      essence: '相手の実際的な必要に気づき、継続的で具体的な形で支えます。',
      visualCues: ['ケア用品、布、カップ、家庭的な物', '穏やかで控えめな姿勢', '柔らかなニット素材'],
      cardUse: 'サービス、細部の記憶、関係への約束のカードに適し、思いやりを具体的に見せます。',
      prompts: ['静かに与えすぎていませんか？', 'どのように助けや承認を求められますか？'],
    },
    ESTJ: {
      title: '効率的マネージャー',
      tone: '直接的、責任感、推進力',
      palette: 'スチールブルー / ニュートラルグレー',
      essence: '明確な基準、役割、進捗を好み、目標を測定可能な実行に変えます。',
      visualCues: ['クリップボード、オフィス、進捗ボード', 'まっすぐな姿勢', 'フォーマルな上着'],
      cardUse: '組織力、説明責任、判断速度のカードに適し、実行型の強みをすばやく伝えます。',
      prompts: ['聞き切る前に最適化を始めていませんか？', 'そのルールは今の状況に合っていますか？'],
    },
    ESFJ: {
      title: 'コミュニティの世話役',
      tone: '外向的、責任感、所属感',
      palette: '空色 / パーティーピンク',
      essence: '実際的な世話と明確な期待で、安定した人間関係の居場所を作ります。',
      visualCues: ['集まり、デザート、歓迎の場面', '友好的な対話姿勢', '明るく柔らかな服装'],
      cardUse: 'チームケア、社交的な気づき、関係維持のカードに適し、温かさと頼もしさを伝えます。',
      prompts: ['好かれることを自己価値と同一視していませんか？', 'より型にはまらない選択を受け入れられますか？'],
    },
    ISTP: {
      title: '冷静な職人',
      tone: '実践的、独立、現場対応',
      palette: 'チャコール / 工具の金属色',
      essence: '直接試すことで世界を理解し、現実の問題に近いほど冷静さを保ちます。',
      visualCues: ['レンチ、機械部品、作業台', 'リラックスしつつ警戒した姿勢', 'レザーやワーク素材'],
      cardUse: '技能、危機時の冷静さ、現場解決のカードに適し、分析を行動場面に近づけます。',
      prompts: ['自分の処理プロセスを早めに説明できますか？', 'どの高リスクなことを早めに計画すべきですか？'],
    },
    ISFP: {
      title: '感性の冒険家',
      tone: '美意識、自由、体験',
      palette: '黄土色 / 自然な緑',
      essence: '感覚、創作、今この瞬間の体験で自分を表し、過度に定義されない自由を重んじます。',
      visualCues: ['スケッチボード、自然風景、カメラ', '静かな観察', '柔らかな重ね着'],
      cardUse: '美的直感、個人のリズム、穏やかな共感のカードに適し、内容を生活感へ移します。',
      prompts: ['長期的にどんな人になりたいですか？', 'どの衝突を積み上がる前に言葉にしますか？'],
    },
    ESTP: {
      title: '行動する起業家',
      tone: '大胆、現実的、機会感覚',
      palette: 'コーラルレッド / 暖かいオレンジ',
      essence: '現場をすばやく読み行動し、交渉、試行錯誤、好機をつかむことに長けています。',
      visualCues: ['都市、車、成長グラフ、動き', '前傾姿勢', '鮮やかな上着とサングラス'],
      cardUse: '即時判断、行動志向、現実的な交渉のカードに適し、速度と機会を感じさせます。',
      prompts: ['結果を軽く見積もっていませんか？', 'どの決定をチームのために記録すべきですか？'],
    },
    ESFP: {
      title: 'ライブの火花',
      tone: '表現的、熱い、寄り添う',
      palette: 'ステージピンク / ゴールド',
      essence: '人を今この瞬間へ連れていき、自然な熱意、励まし、表現力で場を明るくします。',
      visualCues: ['ステージライト、音楽、マイク', '開いた笑顔', 'きらめく素材と明るい色'],
      cardUse: '表現力、社交エネルギー、実践的な励ましのカードに適し、結果に感情的な記憶を残します。',
      prompts: ['未来のために少し取捨選択が必要ですか？', '何が注意を散らしていますか？'],
    },
  },
  ko: {
    INTJ: {
      title: '전략 설계자',
      tone: '침착함, 선견지명, 체계적',
      palette: '딥 퍼플 / 블루 그레이',
      essence: '복잡한 목표를 장기 시스템으로 바꾸며, 독립적인 추론과 높은 품질의 결정을 선호합니다.',
      visualCues: ['건축 설계도와 기하학 모델', '절제된 자세', '어두운 터틀넥과 구조적인 아우터'],
      cardUse: '장기 계획, 독립적 사고, 전략적 강점 카드에 잘 맞으며 이성적이고 미래지향적인 첫인상을 줍니다.',
      prompts: ['가장 최적화하고 싶은 시스템은 무엇인가요?', '내 추론 과정을 너무 늦게 공유하고 있나요?'],
    },
    INTP: {
      title: '논리 분석가',
      tone: '호기심, 정밀함, 추상성',
      palette: '블루 바이올렛 / 잉크색',
      essence: '개념을 분해하고 가설을 검증하며, 아이디어 뒤의 근본 논리를 추적하는 것을 좋아합니다.',
      visualCues: ['노트북과 추상 도형', '생각에 잠긴 시선', '가벼운 학구적 의상'],
      cardUse: '개념의 깊이, 문제 분해, 지속 탐색을 담는 카드에 적합해 사고 실험실 같은 인상을 만듭니다.',
      prompts: ['이 문제의 진짜 변수는 무엇인가요?', '완벽함을 추구하다가 완료를 미루고 있나요?'],
    },
    ENTJ: {
      title: '지휘관',
      tone: '결단력, 조직력, 목표감',
      palette: '네이비 / 실버 그레이',
      essence: '비전을 로드맵으로 바꾸고 자원, 역할, 리듬을 목표에 맞게 정렬합니다.',
      visualCues: ['지도, 체스 말, 계획 보드', '열린 어깨선과 직선적인 시선', '수트형 실루엣'],
      cardUse: '리더십, 실행 질서, 목표 관리 카드에 적합하며 시각적으로 명확한 방향감을 만듭니다.',
      prompts: ['누구에게 더 일찍 반대 의견을 요청해야 하나요?', '효율 외에 어떤 사람의 비용이 있나요?'],
    },
    ENTP: {
      title: '창의적 토론가',
      tone: '민첩함, 확산적 사고, 실험성',
      palette: '보라 / 일렉트릭 블루',
      essence: '관점을 충돌시키고 새 경로를 시험하며 빠른 연상으로 더 날카로운 해결책을 찾습니다.',
      visualCues: ['포스트잇, 프로토타입, 작은 장치', '역동적인 손짓', '편하지만 흐트러지지 않은 스타일'],
      cardUse: '아이디어 생성, 토론 관점, 혁신 돌파 카드에 적합하며 유연함과 관성에 대한 도전을 강조합니다.',
      prompts: ['문제를 진전시키고 있나요, 아니면 새로움만 좇고 있나요?', '어떤 아이디어를 실제로 실행해야 하나요?'],
    },
    INFJ: {
      title: '통찰 옹호자',
      tone: '온화함, 단단함, 의미감',
      palette: '포레스트 그린 / 웜 골드',
      essence: '사람의 가능성을 보고 가치관을 조용하지만 지속적인 행동으로 바꿉니다.',
      visualCues: ['램프, 책, 식물 배경', '보호적인 손짓', '부드럽지만 집중된 표정'],
      cardUse: '사명, 공감, 깊은 통찰 카드에 적합하며 독자가 규정당하기보다 이해받는 느낌을 줍니다.',
      prompts: ['진짜 지키고 싶은 가치는 무엇인가요?', '감정 노동을 혼자 너무 많이 떠안고 있나요?'],
    },
    INFP: {
      title: '이상주의 중재자',
      tone: '진정성, 상상력, 가치 중심',
      palette: '세이지 그린 / 가든 핑크',
      essence: '진정성과 의미를 중시하며 창작, 글, 부드러운 지지로 내면의 신념을 표현합니다.',
      visualCues: ['다이어리, 꽃, 책', '수줍고 몽환적인 표정', '부드러운 소재와 자연색'],
      cardUse: '“어떤 INFP 이미지가 나를 대표하는가”에 가장 잘 맞으며, 내면 가치와 민감함, 창의성을 선택 가능한 버전으로 만듭니다.',
      prompts: ['지금 가장 충실하고 싶은 내면의 목소리는 무엇인가요?', '내 이상을 소진으로부터 지켜줄 구조는 무엇인가요?'],
    },
    ENFJ: {
      title: '따뜻한 안내자',
      tone: '격려, 연결, 이끌기',
      palette: '블루 그린 / 따뜻한 빛',
      essence: '집단의 분위기를 자연스럽게 읽고 사람들을 의미 있는 방향으로 모읍니다.',
      visualCues: ['집단, 교육, 커뮤니티 단서', '열린 손짓', '친근하고 분명한 눈빛'],
      cardUse: '소통, 이끌기, 타인의 성장 지원 카드에 적합하며 관계를 모으는 힘을 보여줍니다.',
      prompts: ['다른 사람이 선택해야 할 몫까지 대신 지고 있나요?', '나의 경계는 어디에 있나요?'],
    },
    ENFP: {
      title: '영감의 시작자',
      tone: '열정, 자유, 가능성',
      palette: '청록 / 밝은 노랑',
      essence: '감염력 있는 에너지로 새 가능성을 열고 사람, 이야기, 아이디어를 연결합니다.',
      visualCues: ['컬러 포스트잇과 브레인스토밍 벽', '큰 표정과 손짓', '가볍고 선명한 아우터'],
      cardUse: '창의적 불꽃, 관계 에너지, 탐색 욕구 카드에 적합해 분석이 정적인 결론에 머물지 않게 합니다.',
      prompts: ['어떤 아이디어에 지속 행동을 남겨야 하나요?', '어떤 선택이 잠깐의 흥분일 뿐인가요?'],
    },
    ISTJ: {
      title: '질서 있는 실행자',
      tone: '신뢰성, 세부, 기준',
      palette: '웜 그레이 / 인디고',
      essence: '사실, 책임, 재사용 가능한 절차를 중시하며 약속을 안정적인 행동으로 옮깁니다.',
      visualCues: ['폴더, 표, 정돈된 선반', '바른 자세', '실용적이고 절제된 옷차림'],
      cardUse: '책임감, 규칙 의식, 안정적인 전달 카드에 적합하며 명확하고 믿음직한 인상을 줍니다.',
      prompts: ['지키고 있는 것이 필요한 기준인가요, 오래된 습관인가요?', '새로운 방법을 위한 여지는 어디에 있나요?'],
    },
    ISFJ: {
      title: '세심한 보호자',
      tone: '배려, 안정, 돌봄',
      palette: '따뜻한 베이지 / 연한 파랑',
      essence: '타인의 실제 필요를 민감하게 포착하고 지속적이고 구체적인 방식으로 지원합니다.',
      visualCues: ['돌봄 물건, 천, 컵, 집 같은 소품', '온화하고 낮은 자세', '부드러운 니트 소재'],
      cardUse: '봉사, 세부 기억, 관계에 대한 약속 카드에 적합하며 돌봄을 추상적이지 않게 보여줍니다.',
      prompts: ['조용히 과하게 주고 있나요?', '어떻게 도움과 인정을 요청할 수 있나요?'],
    },
    ESTJ: {
      title: '효율적 관리자',
      tone: '직접적, 책임감, 추진력',
      palette: '스틸 블루 / 뉴트럴 그레이',
      essence: '명확한 기준, 역할, 진척을 좋아하며 목표를 측정 가능한 실행으로 바꿉니다.',
      visualCues: ['클립보드, 사무실, 진행 보드', '곧은 자세', '포멀한 재킷'],
      cardUse: '조직력, 책임 체계, 결정 속도 카드에 적합해 실행형 강점을 빠르게 이해하게 합니다.',
      prompts: ['충분히 듣기 전에 최적화부터 시작하고 있나요?', '그 규칙은 현재 상황에 맞나요?'],
    },
    ESFJ: {
      title: '공동체 돌봄가',
      tone: '외향성, 책임감, 소속감',
      palette: '하늘색 / 파티 핑크',
      essence: '실제적인 돌봄과 명확한 기대를 통해 안정적인 관계의 소속감을 만듭니다.',
      visualCues: ['모임, 디저트, 환영 장면', '친근한 상호작용 자세', '밝고 부드러운 옷차림'],
      cardUse: '팀 돌봄, 사회적 민감성, 관계 유지 카드에 적합하며 따뜻함과 의지할 수 있음을 전달합니다.',
      prompts: ['호감받는 것을 자기 가치와 동일시하고 있나요?', '덜 전통적인 선택도 받아들일 수 있나요?'],
    },
    ISTP: {
      title: '침착한 장인',
      tone: '실전형, 독립적, 현장 대응',
      palette: '차콜 / 공구 금속색',
      essence: '직접 테스트하며 세계를 이해하고 실제 문제에 가까울수록 침착함을 유지합니다.',
      visualCues: ['렌치, 기계 부품, 작업대', '편하지만 경계하는 자세', '가죽 또는 워크웨어 소재'],
      cardUse: '기술, 위기 속 침착함, 현장 문제 해결 카드에 적합해 분석을 행동 장면에 가깝게 만듭니다.',
      prompts: ['내 처리 과정을 더 일찍 설명할 수 있나요?', '어떤 고위험 일을 더 일찍 계획해야 하나요?'],
    },
    ISFP: {
      title: '감성 모험가',
      tone: '미감, 자유, 경험',
      palette: '오커 / 자연 초록',
      essence: '감각, 창작, 현재의 경험으로 자신을 표현하며 과하게 정의되지 않는 자유를 중시합니다.',
      visualCues: ['스케치 보드, 자연 풍경, 카메라', '조용한 관찰', '부드러운 레이어드 스타일'],
      cardUse: '미적 직관, 개인 리듬, 부드러운 공감 카드에 적합해 내용을 글에서 생활감으로 옮깁니다.',
      prompts: ['장기적으로 어떤 사람이 되고 싶나요?', '어떤 갈등을 쌓이기 전에 말해야 하나요?'],
    },
    ESTP: {
      title: '행동형 사업가',
      tone: '대담함, 현실감, 기회감',
      palette: '코랄 레드 / 웜 오렌지',
      essence: '현장을 빠르게 읽고 행동하며 협상, 시행착오, 타이밍 포착에 강합니다.',
      visualCues: ['도시, 자동차, 성장 그래프, 움직임', '앞으로 기운 자세', '선명한 재킷과 선글라스'],
      cardUse: '즉시 판단, 행동 선호, 현실적 협상 카드에 적합하며 속도와 기회감을 줍니다.',
      prompts: ['결과를 과소평가하고 있나요?', '어떤 결정을 팀을 위해 기록해야 하나요?'],
    },
    ESFP: {
      title: '현장의 불꽃',
      tone: '표현, 열기, 동행',
      palette: '스테이지 핑크 / 골드',
      essence: '사람들을 현재의 경험으로 끌어오고 진짜 열정, 격려, 표현력으로 공간을 밝힙니다.',
      visualCues: ['무대 조명, 음악, 마이크', '활짝 열린 미소', '반짝이는 소재와 밝은 색'],
      cardUse: '표현력, 사회적 에너지, 실천적 격려 카드에 적합해 결과 페이지에 감정적 기억을 남깁니다.',
      prompts: ['미래를 위해 지금 약간의 선택과 포기가 필요한가요?', '무엇이 내 주의를 흩트리고 있나요?'],
    },
  },
};

export function localizeAvatarType(item, locale) {
  const localized = MBTI_AVATAR_TRANSLATIONS[locale]?.[item.type];
  return localized ? { ...item, ...localized } : item;
}

export const MBTI_AVATAR_IMAGES = Object.fromEntries(
  MBTI_AVATAR_TYPES.flatMap(({ type }) => {
    const key = type.toLowerCase();
    return [
      [`${type}-female`, `/assets/mbti-avatars/${key}-female.png`],
      [`${type}-male`, `/assets/mbti-avatars/${key}-male.png`],
    ];
  }),
);
