import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { GENERIC_TESTS } from '../src/pages/quiz/genericTestData.js';

const DISCOVERY_TERMS = [
  'test',
  'quiz',
  'assessment',
  'inventory',
  'questionnaire',
  'scale',
  'profile',
  'personality test',
  'free online',
];

function compactSearchText(test) {
  const tokens = [
    test.slug,
    test.slug.replaceAll('-', ' '),
    ...test.dimensions.map((dimension) => dimension.label),
  ]
    .filter(Boolean)
    .join(' ')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/);

  return [...new Set(tokens)].join(' ');
}

const catalog = GENERIC_TESTS.map((test) => ({
  slug: test.slug,
  title: test.title,
  description: test.intro,
  category: test.category,
  time: test.time,
  questions: test.questions.length,
  href: `/${test.slug}.html`,
  searchText: compactSearchText(test),
}));

const source = [
  '// This file is generated by scripts/generate-catalog.mjs. Do not edit by hand.',
  `export const GENERATED_TEST_CATALOG = ${JSON.stringify(catalog)};`,
  '',
].join('\n');

const testModuleDir = 'src/data/generated-tests';
rmSync(testModuleDir, { recursive: true, force: true });
mkdirSync(testModuleDir, { recursive: true });

GENERIC_TESTS.forEach((test) => {
  writeFileSync(
    `${testModuleDir}/${test.slug}.js`,
    [
      '// This file is generated by scripts/generate-catalog.mjs. Do not edit by hand.',
      `export default ${JSON.stringify(test, null, 2)};`,
      '',
    ].join('\n'),
  );
});

const loaderSource = [
  '// This file is generated by scripts/generate-catalog.mjs. Do not edit by hand.',
  'export const TEST_LOADERS = {',
  ...GENERIC_TESTS.map((test) => `  ${JSON.stringify(test.slug)}: () => import("./generated-tests/${test.slug}.js").then((module) => module.default),`),
  '};',
  '',
].join('\n');

writeFileSync('src/data/generatedTestCatalog.js', source);
writeFileSync('src/data/generatedTestLoaders.js', loaderSource);
console.log(`Generated ${catalog.length} catalog entries and per-test modules.`);
